### PR TITLE
Find By PrimaryKey Extention

### PR DESCRIPTION
**Pull request by SergeyIlyin**

### CODE REVIEW

**Comment by SergeyIlyin** [comment]
This is modifed code from pullRequest of https://github.com/WildGums/Orc.FilterBuilder/pull/39
The modify=> the Key Is **Not** Nulleble<T>

**Comment by SergeyIlyin** [comment]
I closing pull request.
After the last code update, the Find (IDictionary <string, object>) function refers more likely to the EntityFrameworkCore

**Comment by NickStrupat** [comment]
I apologize, I don't understand. Are you saying that EF Core 2.0 has something that makes your `BuildExpression` unnecessary?

**Comment by SergeyIlyin** [comment]
I not found other `BuildExpression`.

After update code to **IQueryable<TEntity>.Find(IDictionary<string, object>)**  the code began to clash with  **IQueryable<TEntity>.Find(object[]).** And works with **IIncludableQueryable** only. 

My code can be used in construction like
```
Expression<Func<TEntity, bool>> expression= iDictionary<string,object>.BuildLambda<TEntity>();
Expression<Func<TEntity, bool>> expression= primaryKeyDictionary.BuildLambda();
IQueryable<TEntity>.FirstOrDefault(expression);
```

I'm happy to override the request if there is enough `BuildLamba() `extension for `PrimaryCodeDictionary` and `BuildLamba<TEntity>()` for `IDictionary<string, object>`.

**Pull request closed without merging**
